server:
  port: 8101
spring:
  main:
    allow-bean-definition-overriding: true
  #####DruidDataSource配置#####################
  type: com.alibaba.druid.pool.DruidDataSource
  initialSize: 5
  minIdle: 5
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall,slf4j
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #合并多个DruidDataSource的监控数据
  useGlobalDataSourceStat: true
  application:
    name: @projectName@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # 数据库配置

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.108.49.84:4078/auth
    KaSecurityUsername: root
    password: wzl20030211
  # Redis 配置

  redis:
    database: 1
    host: 47.108.49.84
    port: 3345
    timeout: 5000
    password: wzl20030211
  # Elasticsearch 配置

  elasticsearch:
    uris: http://localhost:9200
    KaSecurityUsername: root
    password: wzl20030211